### ISSUE TITLE
solawi.ch Roadmap

### ISSUE THREAD

**Issue by cnrk** [teikei/teikei#150]
## internal tasks:
-  [x] Migration to React/Redux, get rid of Backbone/Marionette (#140, #139, #14)
-  [ ] reproduce and fix password change issue reported by user (#151)
-  [x] fix order of search results, cities should be listed with higher priority than adresses (#5)
-  [x] null-pointer exception in certain search results should be caught (#152)
 
## solawi.ch tasks:
- [x] Make map embeddable, create 'teikei widget' (#147)
- [x] widget can be configured to center the map to different locations (#154)
- [x] all map elements (navigation!) have to be rendered client-side to make them embeddable on a div. also we need to think about how to make it responsive, especially as it is a 'widget navigation' and collides with the 'main navigation' of the website. 
- [x] adapt styling of widget to solawi.ch (for ernte-teilen.org we still use the current styling), make sure map styles are separated from the ernte-teilen webpage styles
- [x] new features: user can add 'initiatives'  (#6)
