### ISSUE TITLE
Add a way to create a "initiative"

### ISSUE THREAD

**Issue by zonque** [teikei/teikei#6]
People who want to join a network but can't any in the neighborhood should be able to create an "initiative". The idea is that such people are informed when a new farm is registered in their range. Probably such entries should also time out after a while in order to avoid orphans.

**Comment by cnrk** [comment]
## tasks
- [ ] Add new place type 'initiative'
- [ ] Create new marker icon
- [ ] Create new initiative entry form
- [ ] Update clustering to include initiatives

## form fields
- name  (required) 
- description (required)
- place with geocoder (required)
- contact (same as depot/farm via account information)
